### ISSUE TITLE
1.20.1无法正常运作

### ISSUE THREAD

**Issue by Ethanolgie** [GregTaoo/IconRenderer#2]
可以导出方块和物品，但无法渲染实体，导致最后未能导出JSON文件。
可以完全导出Minecraft内容，但模组内容无法导出。

[latest.log](https://github.com/user-attachments/files/17514211/latest.log)
日志如文件所示。

**Comment by GregTaoo** [comment]
已了解相关情况

**Comment by GregTaoo** [comment]
疑似该模组没有为某个LivingEntity提供renderer
现在已加入判断机制，如果无法渲染则跳过。

**Comment by GregTaoo** [comment]
已发布针对1.20.1 IconR 2.0的补丁，版本号 2.0.1
可去mcmod下载

**Comment by Ethanolgie** [comment]
谢谢

**Comment by Ethanolgie** [comment]
> 已发布针对1.20.1 IconR 2.0的补丁，版本号 2.0.1 可去mcmod下载

导出问题已经解决了，要是能解决一下没人审的问题就好了XwX
